### ISSUE TITLE
YAML Diagram - straight lines

### ISSUE THREAD

**Issue by tyrcho** [plantuml/plantuml#1051]
Hi,

I did not manage to force `straight` or `ortho` lines in a yaml diagram.

here is the code I tried (with or without the 2 commented lines, it has no effect)

```
@startyaml
'skinparam useBetaStyle false
'skinparam linetype ortho

stages:
  - build
  - test

build-code-job:
  stage: build
  script:
    - echo "Check the ruby version, then build some Ruby project files:"
    - ruby -v
    - rake

test-code-job1:
  stage: test
  script:
    - echo "If the files are built successfully, test some files with one command:"
    - rake test1

test-code-job2:
  stage: test
  script:
    - echo "If the files are built successfully, test other files with a different command:"
    - rake test2

@endyaml

``` 

![http://www.plantuml.com/plantuml/uml/hPAnRiCW48PtdkAKfKiy96Ecg9swjaz0y4yXnfp5dLFvxIkmQbcLidNZ-B__-0QkehReOiTaNcI8URB5ZZGBNg7sKvS4yZO9zccA6RfC82uQs1XH-mMv6AAERdDCVJifH8rfS-UuHtVdMsKQVTb0SILEMeDQWWjCXxS0Dv06K9bl2prG978-rfky5abu17tKT2fyXrFoCK4kXtNHMkmUlvCTO4mrsbHEEvSQF55vzysZBITRq9vNajavYFWvfUNO-glHodr73SGPv7WSRUutg-hHwDCVc_D_sx06bBsEfJvwZuAipxNEnboH-_eTVW00](http://www.plantuml.com/plantuml/png/hPAnRiCW48PtdkAKfKiy96Ecg9swjaz0y4yXnfp5dLFvxIkmQbcLidNZ-B__-0QkehReOiTaNcI8URB5ZZGBNg7sKvS4yZO9zccA6RfC82uQs1XH-mMv6AAERdDCVJifH8rfS-UuHtVdMsKQVTb0SILEMeDQWWjCXxS0Dv06K9bl2prG978-rfky5abu17tKT2fyXrFoCK4kXtNHMkmUlvCTO4mrsbHEEvSQF55vzysZBITRq9vNajavYFWvfUNO-glHodr73SGPv7WSRUutg-hHwDCVc_D_sx06bBsEfJvwZuAipxNEnboH-_eTVW00)

This would be useful when drawing a more complex CI file.
