### ISSUE TITLE
Describe diagram in yaml/json format

### ISSUE THREAD

**Issue by Sergey-Terekhin** [plantuml/plantuml#1597]
**Is your feature request related to a problem? Please describe.**
Nowdays json/yaml are pretty popular languages for machine-readable specifications like OpenApi or AsyncApi. But to describe diagrams as code I need to learn pretty outdated and a bit wierd syntax in some places (in my own opinion) without rich editor support. 

**Describe the solution you'd like**
It would be great if PlantUML diagram could be described as yaml/json tree (yaml is more preferrable as it supports comments). In my opinion, it will allow to simplify sintax, to make it more extensible and even more human-readable. The definition of a diagram in yaml can be like this:
```yaml
plantuml:
   type: sequence
   theme: 'awesome visual theme'
   include: '#/variables/actor'                         #reference can be added to the section in current file (or $ref keyword can be used as common for references)
   include: 'common.yaml#/variables/actor'   #or to the external file
```

Existing yaml/json support can be preserved by not specifying diagram type:

**Comment by arnaudroques** [comment]
Even if I personally do not like YAML, I must say that this is an interesting suggestion.

Supporting two syntaxes (the actual one and the new YAML one) would be possible.
I think that the real issue is to find a nice syntax.
Somehow, finding the syntax is more difficult that coding it.

If you have some times, you can help us to find out this syntax.
Let's start by simple examples:

How would you "translate" this simple one:

```
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response
@enduml
```

Something like this?

```
@startyuml
plantuml:
   type: sequence
   actor: Alice
   ....  
@endyuml
```

Please be creative :-)

**Comment by trimble** [comment]
Here's my first brainstorm on how to represent that example into YAML. Submitted mostly to spark further discussion because I think I like this crazy idea.
```
@startyuml
plantuml:
  type: sequence
  actors:
    - Alice
    - Bob
  messages:
    - [Alice, Bob, "Authentication Request"]
    - [Bob, Alice, "Authentication Response", {style: [dotted]}]
    - [Alice, Bob, "Another authentication Request"]
    - [Bob, Alice, "Another authentication Response", {style: [dotted]}]
@endyuml
```
