### ISSUE TITLE
Wrong YAML processing if no spaces at start of list.

### ISSUE THREAD

**Issue by ChameleonRed** [plantuml/plantuml#1876]
**Describe the bug**
YAML diagrem not works with valid YAML.

**To Reproduce**
```yml
@startyaml
first: x
second:
- 1
third:
- name: x
@endyaml
```
http://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000

**Expected behavior**
No spaces should be added artificially to process correctly YAML.
Code beloow works.

```yml
@startyaml
first: x
second:
- 1
third:
  - name: x
@endyaml
```

**Screenshots**
Wrong
![SoWkIImggKpCpU7YIiiiAYwnKgZWAavDpizBiUBILJ3aAid8B08pyn9pKq6IN5mEgNaf81q0](https://github.com/user-attachments/assets/f4dd6cdc-e26e-4d34-bffd-44bef779868f)

Better
![SoWkIImggKpCpU7YIiiiAYwnKgZWAavDpizBiUBILJ3aAid8B08o5HHq5V8ISrD1qbnS3gbvAI0z0000](https://github.com/user-attachments/assets/8a88d83c-f86c-4988-a9cd-5fe017fd31e8)

**Desktop (please complete the following information):**

No matter.
**Smartphone (please complete the following information):**

No matter.

**Additional context**
No.
