### ISSUE TITLE
Allow colon character (`:`) on the value of a YAML field (on a YAML frontmatter)

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#2063]
## Context
To follow:
- #1980
- f3a5610
- 50ded0a
- 9b83249

## Wanted feature
- Could you allow colon character (`:`) on the value of a YAML field _(on a YAML frontmatter)_?

## Not working example ❌ 

From this YAML frontmatter:
```yml
name: vibrant
display_name: Vibrant
description: The vibrant theme from https://github.com/future-architect/puml-themes
author: [future-architect](https://github.com/future-architect)
source: https://github.com/future-architect/puml-themes/tree/master/themes
inspiration: 
```

Here is the plantuml output:
```puml
@startjson
!theme vibrant
%get_current_theme()
@endjson
```
>[![](https://img.plantuml.biz/plantuml/dsvg/SoWkIImgoIhEp-FbKYp9ICrDLIZBJ2fAp2lXvL9DJos9JoujAahDAua7osbeyd8vfEQbWDG30000)](https://editor.plantuml.com/uml/SoWkIImgoIhEp-FbKYp9ICrDLIZBJ2fAp2lXvL9DJos9JoujAahDAua7osbeyd8vfEQbWDG30000) 

Where all values containing a colon are currently not display.

---

Hint of code to change:
https://github.com/plantuml/plantuml/blob/0f28791bf740ed6e069aea765a7aa2e4b1073f22/src/net/sourceforge/plantuml/preproc/ReadLineWithYamlHeader.java#L75-L81

Or perhaps use your `SimpleYamlParser` _(in order to manage more complex YAML source)_:
- https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/yaml/SimpleYamlParser.java

Regards,
Th.
