### ISSUE TITLE
Add YAML data diagram, same concept as JSON data

### ISSUE THREAD

**Issue by Piotr1215** [plantuml/plantuml#434]
It would be beneficial to have YAML data diagram similar to JSON data.

This feature would be useful in representing Kubernetes and docker-compose files.

**Comment by arnaudroques** [comment]
Nice idea!

We've done literally 2 tests :

```
@startyaml
FOO1: bar1
FOO2: bar2
@endyaml
```

and 

```
@startyaml
# hash is a named-tuple structure
hash:
  # value is text
  name1:
    Text
  # value is hash
  name2:
    key: val
  # value is list
  name3:
    - HashOfList1
    - HashOfList2
@endyaml
```

So you can try last beta http://beta.plantuml.net/plantuml.jar or [the online server](http://www.plantuml.com/plantuml/uml/PSun2eD048NXVa_nmDf2qrbPfWYaoGM6E479Ac5dDiJRPn_QYEtxlu7fpINvAdCC5KQn4PD1iCYiG-tv4nNcAJyz9mtiNG0gV2Lc9NNzULde6oRWmULWUBQRTZDlNJlseukJ-UukcwjnBRVtrwsKvhIqeTTbuEz_).

Since there must be many issues, please report here crashes you'll find !

Thanks !
